source 'https://supermarket.chef.io'
cookbook 'nodejs', git:'https://github.com/redguide/nodejs.git'
cookbook 'python'
cookbook 'mongodb-10gen', '~> 0.4.1'
cookbook 'apt'
cookbook 'mongodb3', '~> 5.3.0'
cookbook 'ark'
cookbook 'build-essential'
